### PR TITLE
Validate samples (including metric name).

### LINKED ISSUE #212: Validate samples as they come in
To prevent the ingesters failing to flush chunks when constructing keys.

Should validate according to https://prometheus.io/docs/concepts/data_model/

Need to work out a better way of dealing with nulls in label values.

### PR DESCRIPTION
**Pull request by tomwilkie**
And tests!

Fixes #212

### CODE REVIEW

File: util/validate.go [hunk 1]
```diff
@@ -1,19 +1,42 @@
...
 
 import (
-	"fmt"
 	"regexp"
 
 	"github.com/prometheus/common/model"
 )
 
-var validLabelRE = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)
+// Error see https://dave.cheney.net/2016/04/07/constant-errors
```
Comment (jml) [inline util/validate.go]: All of this has happened before. All of this will happen again.

File: util/validate.go [hunk 2]
```diff
@@ -1,19 +1,42 @@
...
+type Error string
+
+func (e Error) Error() string { return string(e) }
+
+// Errors returned by ValidateSample
+const (
+	ErrMissingMetricName = Error("sample missing metric name")
+	ErrInvalidMetricName = Error("sample invalid metric name")
```
Comment (jml) [inline util/validate.go]: Probably useful to put "name" in quotes here, to indicate that we are missing the metric called 'name'.

Comment (tomwilkie) [inline util/validate.go]: Strictly we're missing a label called `__name__`, but this is referred to as the metric name.  So if anything, we should quote the whole "metric name", but then thats looks weird.  WDYT?
