### PR TITLE
Quietly truncate queries ranging into future

### LINKED ISSUE #472: Queries that range into the future result in table resource not found errors
When using Grafana backed by Cortex, choosing the 'This Month' time range results in all graphs failing to render with the following error:

screenshot from 2017-06-28 15-31-16

Presumably because the periodic tables for future weeks have not yet been created in dynamoDB.

Queries that range into the future should return no data rather than this error.

### PR DESCRIPTION
**Pull request by meccanorak**
To fix #472
Grafana queries for current month/year would mostly fail due to
weekly tables not existing into future.
Fix is to detect when end of time range is future and quietly change to now

### CODE REVIEW

File: pkg/chunk/chunk_store.go [hunk 1]
```diff
@@ -151,6 +151,12 @@ func (c *Store) calculateDynamoWrites(userID string, chunks []Chunk) (WriteBatch
 
 // Get implements ChunkStore
 func (c *Store) Get(ctx context.Context, from, through model.Time, allMatchers ...*metric.LabelMatcher) ([]local.SeriesIterator, error) {
+	now := model.Now()
+	if through.After(now) {
+		util.WithContext(ctx).Warnf("Capping TimeSpanHi from future=%v to now=%v", through, now)
+		through = now
```
Comment (aaron7) [inline pkg/chunk/chunk_store.go]: If `from` is also after `now` and this sets `through` to a value before `from`, we would return the `invalid query` error below. 

This may be confusing to the user (as we changed the `through` value internally), so perhaps we could handle this case separately and return no values?

File: pkg/chunk/chunk_store.go [hunk 2]
```diff
@@ -151,6 +151,12 @@ func (c *Store) calculateDynamoWrites(userID string, chunks []Chunk) (WriteBatch
 
 // Get implements ChunkStore
 func (c *Store) Get(ctx context.Context, from, through model.Time, allMatchers ...*metric.LabelMatcher) ([]local.SeriesIterator, error) {
+	now := model.Now()
+	if through.After(now) {
+		util.WithContext(ctx).Warnf("Capping TimeSpanHi from future=%v to now=%v", through, now)
```
Comment (aaron7) [inline pkg/chunk/chunk_store.go]: Do we need to log these? They may be happening frequently (with dashboards etc) and it is only "parsing" the input to remove the need to query data which cannot exist.

Comment (leth) [inline pkg/chunk/chunk_store.go]: I agree, we shouldn't log this normally, I'm open to logging at debug.
In grafana easy to accidentally click a time range that queries into the future (e.g. "this month").

**Comment by meccanorak** [comment]
Thanks to @aaron7 / @leth for beneficial suggestions, all of which I'm happy to incorporate

**Comment by meccanorak** [comment]
Now revised taking on board comments from @aaron7 / @leth 
Receptive to further comments as/when anyone has opportunity to look
