### PR TITLE
Fix empty-label query semantics

### LINKED ISSUE #220: Incorrect `==` and `=~` label matching behavior for empty label values
In Prometheus, a non-existent label `foo` is equivalent to an empty label `foo=""` (in fact, labels with empty values are removed before a series is stored). That is in Prometheus, `{foo=""}` returns all series with no foo label, as does `{foo=~""}`. Cortex currently returns no series for these, because it actually looks for a `foo` label to be present.

I stumbled over this when looking at https://github.com/weaveworks/cortex/pull/191.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #220

### CODE REVIEW

**Comment by juliusv** [comment]
I'm planning on finally giving this a deeper look tomorrow, but feel free to merge in the meantime if urgent.

**Comment by tomwilkie** [comment]
No rush here, I'll wait for you to be happy.

File: util/matchers.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package util
+
+import (
+	"github.com/prometheus/prometheus/storage/metric"
+)
+
+// SplitFiltersAndMatchers splits empty matchers off, which are treated as filters, see #220
+func SplitFiltersAndMatchers(allMatchers []*metric.LabelMatcher) (filters, matchers []*metric.LabelMatcher) {
+	for _, matcher := range allMatchers {
+		if matcher.Match("") {
```
Comment (juliusv) [inline util/matchers.go]: This could be `matcher.MatchesEmptyString()`, but this works as well.

Comment (tomwilkie) [inline util/matchers.go]: The implementation of that function was a bit suspect, so I thought best to skip it...

Comment (juliusv) [inline util/matchers.go]: Yep, it relies on the matcher being initialized via the constructor method (which should be the case), but otherwise it does the same.
