### PR TITLE
Change backoff algorithm to "full jitter"

### LINKED ISSUE #638: Backoff algorithm can fail to back off
Here is a list of gaps between operations, observed on a real Cortex system:

0.05 | 0.11 | 0.10 | 0.11 | 0.18 | 0.50 | 0.21 | 0.29 | 0.60 | 0.25 | 0.15 | 0.41 | 1.13 | 1.02 | 0.64 | 0.46 | 0.49 | 1.28 | 0.97
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

(times in seconds)
We give up after 20 iterations, total time 9.1 seconds. 

The algorithm is "Decorrelated Jitter" from https://www.awsarchitectureblog.com/2015/03/backoff.html, and as far as I can see we implement it correctly, it's just a bad algorithm.

### PR DESCRIPTION
**Pull request by bboreham**
As described at https://www.awsarchitectureblog.com/2015/03/backoff.html

Fixes #638 

The bump in config is to address the point that we used to sleep 50 ms then random between 50 and 150, so if this was unchanged we would sleep rand(0-50) then rand(0-100) which is quite a bit less.

With this change it will sleep rand(0-100) then rand(0-200).
  
(Although my gut feel is this is still too low)

### CODE REVIEW

File: pkg/chunk/aws_storage_client.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ const (
 var backoffConfig = util.BackoffConfig{
 	// Backoff for dynamoDB requests, to match AWS lib - see:
 	// https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/customizations.go
-	MinBackoff: 50 * time.Millisecond,
+	MinBackoff: 200 * time.Millisecond,
```
Comment (rade) [inline pkg/chunk/aws_storage_client.go]: The 50 was based on the comment above - the aws lib backs off 2^n*50ms. Since we are randomising between 0 and MinBackoff, I reckon the figure should be 100, so that the _mean_ is 50.

Comment (bboreham) [reply pkg/chunk/aws_storage_client.go]: That would be correct if we wanted to stay the same. As I said, I felt the old value was too low.

However it would be safer to do these two changes separately, to avoid confusing the effects.

Comment (bboreham) [reply pkg/chunk/aws_storage_client.go]: Changed to 100ms
