### PR TITLE
Address some correctness issues with the v5 schema

### LINKED ISSUE #199: ValidationException writing to DynamoDB
```
time="2017-01-12T09:19:22Z" level=error msg="Failed to flush user: ValidationException: 1 validation error detected: Value '{dev_chunks_2=[com.amazonaws.dynamodb.v20120810.WriteRequest@4e30492f, com.amazonaws.dynamodb.v20120810.WriteRequest@18a2a2a9, com.amazonaws.dynamodb.v20120810.WriteRequest@7ffde57b, com.amazonaws.dynamodb.v20120810.WriteRequest@9351d4a9, com.amazonaws.dynamodb.v20120810.WriteRequest@b3bd633, com.amazonaws.dynamodb.v20120810.WriteRequest@5cb99f27, com.amazonaws.dynamodb.v20120810.WriteRequest@484e1a44, com.amazonaws.dynamodb.v20120810.WriteRequest@6a4d92ed, com.amazonaws.dynamodb.v20120810.WriteRequest@f500982d, com.amazonaws.dynamodb.v20120810.WriteRequest@f93e632a, com.amazonaws.dynamodb.v20120810.WriteRequest@b9be517e, com.amazonaws.dynamodb.v20120810.WriteRequest@b500def7, com.amazonaws.dynamodb.v20120810.WriteRequest@17e208ba, com.amazonaws.dynamodb.v20120810.WriteRequest@49a96b3c, com.amazonaws.dynamodb.v20120810.WriteRequest@9e681938, com.amazonaws.dynamodb.v20120810.WriteRequest@23b8e738, com.amazonaws.dynamodb.v20120810.WriteRequest@8371b0d2, com.amazonaws.dynamodb.v20120810.WriteRequest@c88d47c6, com.amazonaws.dynamodb.v20120810.WriteRequest@364c79d9, com.amazonaws.dynamodb.v20120810.WriteRequest@a6c3f363, com.amazonaws.dynamodb.v20120810.WriteRequest@4d5e6057, com.amazonaws.dynamodb.v20120810.WriteRequest@f44bb374, com.amazonaws.dynamodb.v20120810.WriteRequest@3f4dc3bd, com.amazonaws.dynamodb.v20120810.WriteRequest@9d7c555d, com.amazonaws.dynamodb.v20120810.WriteRequest@19674e5f], dev_chunks_weekly_2454=[]}' at 'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]\n\tstatus code: 400, request id: UDG9TOJUHDKPMCKDV3O800US3FVV4KQNSO5AEMVJF66Q9ASUAAJG" source="ingester.go:568"
```

Seems DynamoDB doesn't like writes with empty lists.

### PR DESCRIPTION
**Pull request by tomwilkie**
Should potentially help with #304 (missing data reported by @rade and @juliusv, but not @Bplotka as he is on v4 schema).

Unfortunately, the way I calculated the relative timestamp of chunks within buckets was wrong, causing overflow of a uint32.  The data written by the v5 schema is incorrect.  This PR adds tests to expose it, and fixes.

The situation is salvageable though - I have made the v5 schema ignore the timestamps for reads.   This will have a performance regression, but I will make a new v6 schema that takes them into account (to help with #199).

### CODE REVIEW

File: chunk/chunk_store_test.go [hunk 1]
```diff
@@ -157,3 +159,84 @@ func mustNewLabelMatcher(matchType metric.MatchType, name model.LabelName, value
...
+				t.Fatal(err)
+			}
+
+			// We need to check that each chunk is in the time range
+			for _, chunk := range chunks {
+				assert.False(t, chunk.From.After(endTime))
+				assert.False(t, chunk.Through.Before(startTime))
+			}
+
+			// And check we go all the chunks we want
```
Comment (juliusv) [inline chunk/chunk_store_test.go]: go -> got

File: chunk/schema.go [hunk 2]
```diff
@@ -106,8 +106,8 @@ func (cfg SchemaConfig) hourlyBuckets(from, through model.Time, userID string, m
 	)
 
 	for i := fromHour; i <= throughHour; i++ {
-		relativeFrom := util.Max64(i*millisecondsInHour, int64(from))
-		relativeThrough := util.Min64((i+1)*millisecondsInHour, int64(through))
+		relativeFrom := util.Max64(0, int64(from)-(i*millisecondsInHour))
```
Comment (juliusv) [inline chunk/schema.go]: I'm having trouble understanding how this works. First, the `relative...` naming is confusing - if I understand correctly, the resulting `relativeFrom` and `relativeThrough` timestamps are used as absolute bucket timestamps in the schema's `GetWriteEntries()` etc. functions. So if that's true, how can it be right to start with a `from` that's X hours earlier than the original `from` and then just go earlier and earlier from there, instead of later? Same for `through`. Also, shouldn't bucket timestamps be hourly-aligned? I don't see how that can be the case when the unaligned `from` is simply added as a term to an aligned value here.

Gah, I'm probably just missing something stupid, but my head doesn't want to wrap around it today?

**Comment by tomwilkie** [comment]
The max will cap it start at zero, so it'll never go negative. Min will cap
end at milliseconds in day (if the chunk after the bucket).

This is complicated enough, and I've got it wrong once already, that it
deserves an explanation.

The idea here is that the hash key constrains the time stamp, rounded to
the nearest bucket (day).  The range key contains the offset from that, to
the (start/end) of the chunk. For chunks that span multiple buckets, these
offsets will be capped to the bucket boundaries. I.e. Start will be
positive in the first bucket, then zero in the next etc.

When when doing writes, we only use the chunk end time stamp.  We then use
the query start time stamp to scan from there to the end of the row to
catch all chunks that end after the query starts.

The reason for doing all this is to reduce the size of the time stamps we
include in the range keys - we use a uint32 - as we then have to base 32
encode it.

**Comment by juliusv** [comment]
@tomwilkie Ooohhh, I think *now* I get it! What's confused me is that originally the `dailyBuckets` and `hourlyBuckets` had different semantics, where they actually produced the from/through of the *buckets*. Now they produce the time ranges of the *chunks*. Right? Makes sense then.

:+1:

**Comment by tomwilkie** [comment]
> where they actually produced the from/through of the buckets. Now they produce the time ranges of the chunks. Right?

Yeah these functions produce the hash keys given a range, and get passed a callback from producing the range keys.  The callback in turn is passed a range, but this time its a sub-range of the first range, and made relative.
