### PR TITLE
Switch to snappy/proto for encoding ring in consul

### LINKED ISSUE #94: Add http endpoint to render ring state in html
To help with debugging.

Should be exposed on ingesters and distributors.

### LINKED ISSUE #156: Error CASing collectors/ring: Unexpected response code: 413 (Value exceeds 524288 byte limit)
The ring has got too big.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #156 

<s>(Includes #162 and #161 for now, until they are merged)</s>

- The ring can read and write json and proto
- Internal representation is all proto, and there is a translation between the two (`ring.go:MarshalJSON`)
- Ingesters will always try to read json first, fallback to proto if that fails
- Once ingester fails to read json, it will always write proto
- Ingester will also start writing proto once it has detected all ingesters can read it

Have testing upgrades from master to this locally

### CODE REVIEW

File: ring/http.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+						<th>Actions</th>
+					</tr>
+				</thead>
+				<tbody>
+					{{ range $key, $value := .Ring.Ingesters }}
+					<tr>
+						<td>{{ $key }}</td>
+						<td>{{ $value.State }}</td>
+						<td>{{ $value.Hostname }}</td>
+						<td>{{ $value.Timestamp | time }}</td>
```
Comment (jml) [inline ring/http.go]: IIRC, this time is from the ingester's clock, but the state is inferred from the distributor's clock. 

Either way, this page should either show the distributor's opinion of the current time outside the table (so we have a basis for comparison), or the delta between the current time and the last heartbeat in the table.

File: ring/consul_client.go [hunk 2]
```diff
@@ -18,18 +20,20 @@ const (
...
 	PutBytes(key string, buf []byte) error
 }
 
 // CASCallback is the type of the callback to CAS.  If err is nil, out must be non-nil.
 type CASCallback func(in interface{}) (out interface{}, retry bool, err error)
 
-// InstanceFactory type creates empty instances for use when deserialising
-type InstanceFactory func() interface{}
+// SerDes allows the consult client to serialise and deserialise values.
+type SerDes interface {
```
Comment (jml) [inline ring/consul_client.go]: `Codec` would be a more traditional name, and would be more consistent with the methods on json & proto.

File: ring/consul_client.go [hunk 3]
```diff
@@ -64,25 +72,112 @@ var (
...
-	if err := json.NewDecoder(bytes.NewReader(kvp.Value)).Decode(out); err != nil {
-		return err
+
+	if !d.useProto {
+		log.Infof("Error decoding json, switching to writing proto: %v", err)
+		d.useProto = true
 	}
-	return nil
+
+	return d.proto.Decode(bytes)
```
Comment (jml) [inline ring/consul_client.go]: The downside of this method is that it will mask genuine JSON errors. A more precise approach would be to figure out exactly _which_ error is returned when we try to decode protobufs as JSON (https://godoc.org/encoding/json has a bunch), and then type assert on that. 

I'm not entirely sure it's worth it, though.

File: ring/consul_client.go [hunk 4]
```diff
@@ -64,25 +72,112 @@ var (
...
+	json     SerDes
+	proto    SerDes
+}
+
+// NewDynamicSerDes makes a new DynamicSerDes
+func NewDynamicSerDes(json, proto SerDes) *DynamicSerDes {
+	return &DynamicSerDes{
+		useProto: false,
+		json:     json,
+		proto:    proto,
```
Comment (jml) [inline ring/consul_client.go]: A different approach would be to have a vector of `SerDes` instead of special `json` and `proto` ones, and an index of the currently selected format, instead of `useProto`. That way this would work with future format changes.

Then the public `UseProto` would become `UseVersion` and the check for `allIngestersCanReadProtos` would instead find the minimum supported version.

Not sure it's worth it though. Would help for future compatibility stuff and for tests (because you could pass much simpler codecs & objects).

File: ring/consul_client.go [hunk 5]
```diff
@@ -64,25 +72,112 @@ var (
...
+
+// Encode implemenrs SerDes
+func (d *DynamicSerDes) Encode(msg interface{}) ([]byte, error) {
+	d.mtx.Lock()
+	defer d.mtx.Unlock()
+	if d.useProto {
+		return d.proto.Encode(msg)
+	}
+	return d.json.Encode(msg)
 }
```
Comment (jml) [inline ring/consul_client.go]: I'd welcome unit tests for `DynamicSerDes`.

File: ring/consul_client.go [hunk 6]
```diff
@@ -140,11 +140,12 @@ func NewDynamicSerDes(json, proto SerDes) *DynamicSerDes {
 
 // UseProto allow you to change the SerDes at runtime.
 func (d *DynamicSerDes) UseProto(useProto bool) {
-	log.Infof("Switching to proto serialization: %v", useProto)
-
 	d.mtx.Lock()
 	defer d.mtx.Unlock()
-	d.useProto = useProto
+	if d.useProto != useProto {
+		log.Infof("Switching to proto serialization: %v", useProto)
```
Comment (jml) [inline ring/consul_client.go]: Except this isn't true. If `useProto` is `false`, then we are switching _away_ from proto encoding.

File: ring/consul_client.go [hunk 7]
```diff
@@ -64,25 +72,113 @@ var (
...
+
+	out, err := d.json.Decode(bytes)
+	if err == nil {
+		return out, nil
 	}
-	return nil
+
+	if !d.useProto {
+		log.Infof("Error decoding json, switching to writing proto: %v", err)
+		d.useProto = true
```
Comment (tomwilkie) [inline ring/consul_client.go]: @jml perhaps I should do this only if `d.proto.Decode` succeeds?

File: ring/consul_client.go (hunk 6 above)
Comment (tomwilkie) [inline ring/consul_client.go]: Will update.

File: ring/consul_client.go (hunk 2 above)
Comment (tomwilkie) [inline ring/consul_client.go]: :+1

File: ring/consul_client.go (hunk 4 above)
Comment (tomwilkie) [inline ring/consul_client.go]: > Not sure it's worth it though.

This.  I intend to delete most of this code once we get into production, and I doubt we'll be doing another move like this in the future, at least to the extent where is worth maintaining this code.

File: ring/consul_client.go (hunk 7 above)
Comment (jml) [inline ring/consul_client.go]: Yes, good thought.

File: ring/ingester_lifecycle.go [hunk 8]
```diff
@@ -165,7 +165,7 @@ func (r *IngesterRegistration) heartbeat(tokens []uint32) {
 			ingesterDesc.Timestamp = time.Now().Unix()
 			ingesterDesc.State = r.state
 
-			// Set ProtoRing back to true for the case where an existing ingester that didn't understand this field removed it whilst updating the ring.
+			// Set ProtoRing back to true for the case where an existing ingestser that didn't understand this field removed it whilst updating the ring.
```
Comment (jml) [inline ring/ingester_lifecycle.go]: :trollface:
