### PR TITLE
Continue to heartbeat to consul whilst flushing / transferring.

### LINKED ISSUE #386: All hell broke loose II - ingesters don't heartbeat during flush
During the great cortex fire of April '17, two ingesters fell back to flushing (from transferring) and during the flush, didn't heartbeat.

This lead to them being marked as dead by the distributor, and we can't tolerate two failed ingester, so the service went offline for ~10mins.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #386

### CODE REVIEW

File: ingester/ingester_lifecycle.go [hunk 1]
```diff
@@ -187,21 +187,29 @@ loop:
...
+	for {
+		select {
+		case <-heartbeatTicker.C:
+			consulHeartbeats.Inc()
+			if err := i.updateConsul(); err != nil {
+				log.Errorf("Failed to write to consul, sleeping: %v", err)
+			}
+
+		case f := <-i.actorChan:
+			f()
```
Comment (jml) [inline ingester/ingester_lifecycle.go]: What do we expect to receive from the `actorChan` during shutdown?

Comment (tomwilkie) [inline ingester/ingester_lifecycle.go]: Hmm good point.  Its only used during the joining process.  Will remove.
