### PR TITLE
Stream chunks from ingester to querier on queries.

### LINKED ISSUE #913: Make ingester -> querier responses streaming
We're seeing 200MB responses:

```
level=error ts=2018-07-31T19:53:37.7193191Z caller=engine.go:525 msg="error selecting series set" err="rpc error: code = ResourceExhausted desc = grpc: received message larger than 
max (200118416 vs. 67108864)"
```

Need to stream them.  Thanos already does this, maybe this can be a chance to unify the API? https://github.com/improbable-eng/thanos/blob/master/pkg/store/storepb/rpc.proto#L18

### PR DESCRIPTION
**Pull request by tomwilkie**
Should reduce CPU load on ingesters & network load as chunks as compressed; generally allows us to do much bigger queries without risk of OOMing the ingester.

Also:
- factor out the replication/consistency handling logic onto a method of `replicationSet`.
- move distributor query methods to separate file, in preparation for removing them from the distributor all together.

Fixes #913

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

File: pkg/distributor/query.go [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+		}
+		return nil
+	})
+	return matrix, err
+}
+
+// QueryStream multiple ingesters via the streaming interface and returns big ol' set of chunks.
+func (d *Distributor) QueryStream(ctx context.Context, from, to model.Time, matchers ...*labels.Matcher) ([]client.TimeSeriesChunk, error) {
+	var result []client.TimeSeriesChunk
+	err := instrument.TimeRequestHistogram(ctx, "Distributor.Query", queryDuration, func(ctx context.Context) error {
```
Comment (gouthamve) [inline pkg/distributor/query.go]: Should be `Distributor.QueryStream`

File: pkg/distributor/query.go [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+func (d *Distributor) queryIngesterStream(ctx context.Context, replicationSet ring.ReplicationSet, req *client.QueryRequest) ([]client.TimeSeriesChunk, error) {
+	// Fetch samples from multiple ingesters
+	results, err := replicationSet.Do(ctx, func(ing *ring.IngesterDesc) (interface{}, error) {
+		client, err := d.ingesterPool.GetClientFor(ing.Addr)
+		if err != nil {
+			return nil, err
+		}
+
+		stream, err := client.(ingester_client.IngesterClient).QueryStream(ctx, req)
+		ingesterQueries.WithLabelValues(ing.Addr).Inc()
```
Comment (gouthamve) [inline pkg/distributor/query.go]: super nit: Move this one line above? It'll keep the err and it's handling near each other.

File: pkg/distributor/query.go [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+			result = append(result, series)
+		}
+		return result, nil
+	})
+	if err != nil {
+		return nil, err
+	}
+
+	hashToSeries := map[model.Fingerprint]ingester_client.TimeSeriesChunk{}
+	for _, result := range results {
```
Comment (gouthamve) [inline pkg/distributor/query.go]: Would a single type assertion here: `results.([][]* ingester_client.QueryStreamResponse)` save several assertions below?

File: pkg/distributor/query.go [hunk 4]
```diff
@@ -0,0 +1,187 @@
...
+				hash := ingester_client.FromLabelPairs(series.Labels).FastFingerprint()
+				existing := hashToSeries[hash]
+				existing.Labels = series.Labels
+				existing.Chunks = append(existing.Chunks, series.Chunks...)
+				hashToSeries[hash] = existing
+			}
+		}
+	}
+	result := make([]client.TimeSeriesChunk, 0, len(hashToSeries))
+	for hash := range hashToSeries {
```
Comment (gouthamve) [inline pkg/distributor/query.go]:
```
for _, series := range hashToSeries {
  result = append(result, series)
}
```

Is this not done this way to avoid copying? Could you add a comment saying so?

File: pkg/ingester/ingester.go [hunk 5]
```diff
@@ -358,12 +356,77 @@ func (i *Ingester) query(ctx context.Context, from, through model.Time, matchers
...
+	i.userStatesMtx.RUnlock()
+	if err != nil {
+		return err
+	} else if !ok {
+		return nil
+	}
+
+	numSeries, numChunks := 0, 0
+	batch := make([]client.TimeSeriesChunk, 0, queryStreamBatchSize)
+	// We'd really like to series series in label order, not FP order, so we
```
Comment (gouthamve) [inline pkg/ingester/ingester.go]: `have series` not `series series`?

File: pkg/distributor/query.go (hunk 4 above)
Comment (tomwilkie) [reply pkg/distributor/query.go]: It appears not:

`./query.go:158:32: invalid type assertion: results.([][]*client.QueryStreamResponse) (non-interface type []interface {} on left)`

File: pkg/distributor/query.go (hunk 3 above)
Comment (tomwilkie) [reply pkg/distributor/query.go]: Apparently not:

`./query.go:158:32: invalid type assertion: results.([][]*client.QueryStreamResponse) (non-interface type []interface {} on left)`

File: pkg/distributor/distributor_test.go [hunk 6]
```diff
@@ -406,6 +416,80 @@ func (i *mockIngester) Query(ctx context.Context, req *client.QueryRequest, opts
...
+				Value:     model.SampleValue(sample.Value),
+			})
+			if err != nil {
+				panic(err)
+			}
+			c = cs[0]
+		}
+
+		chunk := client.Chunk{
+			//StartTimestampMs: int64(),
```
Comment (csmarchbanks) [inline pkg/distributor/distributor_test.go]: Unnecessary comments?

File: pkg/distributor/query.go [hunk 7]
```diff
@@ -0,0 +1,186 @@
...
+	}
+	result := make([]client.TimeSeriesChunk, 0, len(hashToSeries))
+	for _, series := range hashToSeries {
+		result = append(result, series)
+	}
+
+	return result, nil
+}
+
+func fromLabelPairs(in []client.LabelPair) labels.Labels {
```
Comment (csmarchbanks) [inline pkg/distributor/query.go]: This function exists here and in pkg/querier/ingester_streaming_queryable.go, would be nice to consolidate them

**Comment by tomwilkie** [comment]
Thanks @csmarchbanks !
