### PR TITLE
Split up the single Cortex binary into cortex-{distributor, ingester, querier, ruler, table-manager}

### LINKED ISSUE #151: Split up cortex into different binaries / images
`main.go` is becoming a bit of a mess.

### LINKED ISSUE #194: Separate out query service
We're starting to see various panics and bugs arising from query processing, and if they send the distributors into a crash loop, we stop accepting writes.  A separate query service would prevent this.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #194, fixes #151 

- Push flag definitions onto the respective config objects
- Separate binaries for each component
- Add a new component: cortex_querier (currently a dressed up distributor)
- New server package for common server logic
- Makefile magic to decide what services to build
- Nest the consul client in the ring, and the ring in the ingester registerer, as they share config.
- Make the chunk cache initialise itself, and noop if isn't provided a hostname
- Move prometheus.MustRegister into each component to reduce repetition

### CODE REVIEW

File: cmd/cortex-ingester/main.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+	"github.com/weaveworks/cortex/ring"
+	"github.com/weaveworks/cortex/server"
+	"github.com/weaveworks/cortex/util"
+)
+
+func main() {
+	var (
+		serverConfig               = server.Config{}
+		ingesterRegistrationConfig = ring.IngesterRegistrationConfig{
+			ListenPort: &serverConfig.GRPCListenPort, // IngesterRegistrator need to know our gRPC listen port
```
Comment (juliusv) [inline cmd/cortex-ingester/main.go]: need -> needs

File: cmd/cortex-ingester/main.go [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+	"github.com/weaveworks/cortex/chunk"
+	"github.com/weaveworks/cortex/ingester"
+	"github.com/weaveworks/cortex/ring"
+	"github.com/weaveworks/cortex/server"
+	"github.com/weaveworks/cortex/util"
+)
+
+func main() {
+	var (
+		serverConfig               = server.Config{}
```
Comment (juliusv) [inline cmd/cortex-ingester/main.go]: The `var serverConfig = server.Config{}` style here and below is just a bit unusual. More usual would be either `var serverConfig server.Config` or `serverConfig := server.Config{}` (not a mix of `var` and explicit assignment of zero value).

Comment (tomwilkie) [inline cmd/cortex-ingester/main.go]: Fair point, I'll make it this:
```go
var (
  serverConfig server.Config
  ...
)
```

File: util/flags.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
+package util
+
+import (
+	"flag"
+	"time"
+
+	"github.com/prometheus/common/model"
+)
+
+// Registerer is a think that can RegisterFlags
```
Comment (juliusv) [inline util/flags.go]: think -> thing

**Comment by juliusv** [comment]
:+1:

**Comment by juliusv** [comment]
Btw., do we need the `cortex-` prefix in the binary dirs? Since it's all part of Cortex, it seems a bit redundant.

**Comment by tomwilkie** [comment]
> Btw., do we need the cortex- prefix in the binary dirs? Since it's all part of Cortex, it seems a bit redundant.

I'm using it to generate the binary _and_ image name, and image name definitely needs it.  I can include that as a constant in the Makefile though.  Let me give that a go.

**Comment by juliusv** [comment]
:+1:

**Comment by tomwilkie** [comment]
@juliusv @jml I think this is ready to merge now; will do so tomorrow morning unless I hear otherwise?

**Comment by jml** [comment]
Great stuff. 

In person yesterday, you mentioned a pattern for constructors for components. Could you please jot that down in text somewhere in the repo?

**Comment by jml** [comment]
I'll take that as a no.

File: ingester/ingester.go [hunk 4]
```diff
@@ -165,6 +174,7 @@ func New(cfg Config, chunkStore cortex_chunk.Store) (*Ingester, error) {
 			Help: "The total number of samples returned from queries.",
 		}),
 	}
+	prometheus.MustRegister(i)
```
Comment (juliusv) [inline ingester/ingester.go]: @tomwilkie Registering Prometheus metrics from a constructor is problematic because it makes it impossible to instantiate multiple objects of the same type (the Prometheus client library will panic). I'm hitting this with ingester tests right now. While there's a non-panicking `Register` method, neither returning its error nor letting it silently fail seem like the right choice.

I would propose either moving this out of the constructor again or making the metrics global. Which one do you prefer?

Comment (tomwilkie) [inline ingester/ingester.go]: > I'm hitting this with ingester tests right now

Have you written some new tests?  Wondering why I didn't hit it.

> I would propose either moving this out of the constructor again or making the metrics global. Which one do you prefer?

Global please.  For consistency sake, I'd like everything to be global - I'm not concerned about the namespace pollution, and going global results in less code, which is one of the things I care most about.

Comment (juliusv) [inline ingester/ingester.go]: > Have you written some new tests? Wondering why I didn't hit it.

Yeah, I hit this when writing a second ingester test for the series limiting.

> Global please.

Ok, will get to it next week.

FWIW, with having metrics globally, the concern is less about global variable namespace pollution, but about anyone wanting to reuse a package getting globally registered metrics forced on them. As long as we don't care about reuse, that's fine.
