### PR TITLE
Fix flaky chunk tests by being explicit about `now`

### LINKED ISSUE #646: Chunk test flake
Wonder if this is to do with the from/to times I added in `chunksToMatrix`

As seen at https://circleci.com/gh/weaveworks/cortex/1550

````
make: Leaving directory '/go/src/github.com/weaveworks/cortex'

0.07user 0.01system 0:02.73elapsed 2%CPU (0avgtext+0avgdata 13692maxresident)k
0inputs+0outputs (0major+3498minor)pagefaults 0swaps
time docker run  -ti \
		-v /home/ubuntu/cortex/.pkg:/go/pkg \
		-v /home/ubuntu/cortex:/go/src/github.com/weaveworks/cortex \
		quay.io/weaveworks/cortex-build-image test;
make: Entering directory '/go/src/github.com/weaveworks/cortex'

./tools/test -netgo
--- FAIL: TestChunkStore_Get (0.17s)
    --- FAIL: TestChunkStore_Get/foo_/_v1_schema (0.00s)
    	chunk_store_test.go:195: ========= Running query foo with schema v1 schema
    	chunk_store_test.go:225: foo: wrong chunks - 
    		--- want
    		+++ have
    		@@ -1,8 +1,8 @@
    		 (model.Matrix) (len=2 cap=2) (foo{bar="beep", toms="code"} =>
    		-0 @[1515521286.776]
    		+
    		 foo{bar="baz", flip="flop", toms="code"} =>
    		 0 @[1515521286.775]) {
    		- (*model.SampleStream)(0xc4206c32e0)((foo{bar="baz", flip="flop", toms="code"} =>
    		+ (*model.SampleStream)(0xc4200d1980)((foo{bar="baz", flip="flop", toms="code"} =>
    		 0 @[1515521286.775]) {
    		   Metric: (model.Metric) (len=4) (foo{bar="baz", flip="flop", toms="code"}) {
    		    (model.LabelName) (len=8) "__name__": (model.LabelValue) (len=3) "foo",
    		@@ -17,18 +17,14 @@
    		    }
    		   }
    		  }),
    		- (*model.SampleStream)(0xc4206c3300)((foo{bar="beep", toms="code"} =>
    		-0 @[1515521286.776]) {
    		+ (*model.SampleStream)(0xc4200d19a0)((foo{bar="beep", toms="code"} =>
    		+) {
    		   Metric: (model.Metric) (len=3) (foo{bar="beep", toms="code"}) {
    		    (model.LabelName) (len=8) "__name__": (model.LabelValue) (len=3) "foo",
    		    (model.LabelName) (len=3) "bar": (model.LabelValue) (len=4) "beep",
    		    (model.LabelName) (len=4) "toms": (model.LabelValue) (len=4) "code"
    		   },
    		-  Values: ([]model.SamplePair) (len=1 cap=1) {
    		-   (model.SamplePair) (0 @[1515521286.776]) {
    		-    Timestamp: (model.Time) (1515521286.776) 1515521286776,
    		-    Value: (model.SampleValue) (0) 0
    		-   }
    		+  Values: ([]model.SamplePair) {
    		   }
    		  })
    		 }
...
FAIL

FAIL	github.com/weaveworks/cortex/pkg/chunk	5.055s
````

and again on my desktop:

```
./tools/test -netgo
--- FAIL: TestChunkStore_Get (0.20s)
    --- FAIL: TestChunkStore_Get/{__name__!="foo",_toms="code"}_/_v8_schema (0.00s)
    	chunk_store_test.go:195: ========= Running query {__name__!="foo", toms="code"} with schema v8 schema
    	chunk_store_test.go:225: {__name__!="foo", toms="code"}: wrong chunks - 
    		--- want
    		+++ have
    		@@ -1,17 +1,13 @@
    		 (model.Matrix) (len=1 cap=1) (bar{bar="baz", toms="code"} =>
    		-0 @[1515580128.756]) {
    		- (*model.SampleStream)(0xc4212cc1e0)((bar{bar="baz", toms="code"} =>
    		-0 @[1515580128.756]) {
    		+) {
    		+ (*model.SampleStream)(0xc4212cd680)((bar{bar="baz", toms="code"} =>
    		+) {
    		   Metric: (model.Metric) (len=3) (bar{bar="baz", toms="code"}) {
    		    (model.LabelName) (len=8) "__name__": (model.LabelValue) (len=3) "bar",
    		    (model.LabelName) (len=3) "bar": (model.LabelValue) (len=3) "baz",
    		    (model.LabelName) (len=4) "toms": (model.LabelValue) (len=4) "code"
    		   },
    		-  Values: ([]model.SamplePair) (len=1 cap=1) {
    		-   (model.SamplePair) (0 @[1515580128.756]) {
    		-    Timestamp: (model.Time) (1515580128.756) 1515580128756,
    		-    Value: (model.SampleValue) (0) 0
    		-   }
    		+  Values: ([]model.SamplePair) {
    		   }
    		  })
    		 }
    --- FAIL: TestChunkStore_Get/{__name__=~"bar",_bar="baz"}_/_v8_schema (0.01s)
    	chunk_store_test.go:195: ========= Running query {__name__=~"bar", bar="baz"} with schema v8 schema
    	chunk_store_test.go:225: {__name__=~"bar", bar="baz"}: wrong chunks - 
    		--- want
    		+++ have
    		@@ -1,32 +1,24 @@
    		 (model.Matrix) (len=2 cap=2) (bar{bar="baz"} =>
    		-0 @[1515580128.756]
    		+
    		 bar{bar="baz", toms="code"} =>
    		-0 @[1515580128.756]) {
    		- (*model.SampleStream)(0xc4212cc1c0)((bar{bar="baz"} =>
    		-0 @[1515580128.756]) {
    		+) {
    		+ (*model.SampleStream)(0xc420228740)((bar{bar="baz"} =>
    		+) {
    		   Metric: (model.Metric) (len=2) (bar{bar="baz"}) {
    		    (model.LabelName) (len=8) "__name__": (model.LabelValue) (len=3) "bar",
    		    (model.LabelName) (len=3) "bar": (model.LabelValue) (len=3) "baz"
    		   },
    		-  Values: ([]model.SamplePair) (len=1 cap=1) {
    		-   (model.SamplePair) (0 @[1515580128.756]) {
    		-    Timestamp: (model.Time) (1515580128.756) 1515580128756,
    		-    Value: (model.SampleValue) (0) 0
    		-   }
    		+  Values: ([]model.SamplePair) {
    		   }
    		  }),
    		- (*model.SampleStream)(0xc4212cc1e0)((bar{bar="baz", toms="code"} =>
    		-0 @[1515580128.756]) {
    		+ (*model.SampleStream)(0xc420228720)((bar{bar="baz", toms="code"} =>
    		+) {
    		   Metric: (model.Metric) (len=3) (bar{bar="baz", toms="code"}) {
    		    (model.LabelName) (len=8) "__name__": (model.LabelValue) (len=3) "bar",
    		    (model.LabelName) (len=3) "bar": (model.LabelValue) (len=3) "baz",
    		    (model.LabelName) (len=4) "toms": (model.LabelValue) (len=4) "code"
    		   },
    		-  Values: ([]model.SamplePair) (len=1 cap=1) {
    		-   (model.SamplePair) (0 @[1515580128.756]) {
    		-    Timestamp: (model.Time) (1515580128.756) 1515580128756,
    		-    Value: (model.SampleValue) (0) 0
    		-   }
    		+  Values: ([]model.SamplePair) {
    		   }
    		  })
    		 }
    --- FAIL: TestChunkStore_Get/{__name__=~"bar",_bar="baz",toms!="code"}_/_v8_schema (0.00s)
    	chunk_store_test.go:195: ========= Running query {__name__=~"bar", bar="baz",toms!="code"} with schema v8 schema
    	chunk_store_test.go:225: {__name__=~"bar", bar="baz",toms!="code"}: wrong chunks - 
    		--- want
    		+++ have
    		@@ -1,16 +1,12 @@
    		 (model.Matrix) (len=1 cap=1) (bar{bar="baz"} =>
    		-0 @[1515580128.756]) {
    		- (*model.SampleStream)(0xc4212cc1c0)((bar{bar="baz"} =>
    		-0 @[1515580128.756]) {
    		+) {
    		+ (*model.SampleStream)(0xc4212cc0e0)((bar{bar="baz"} =>
    		+) {
    		   Metric: (model.Metric) (len=2) (bar{bar="baz"}) {
    		    (model.LabelName) (len=8) "__name__": (model.LabelValue) (len=3) "bar",
    		    (model.LabelName) (len=3) "bar": (model.LabelValue) (len=3) "baz"
    		   },
    		-  Values: ([]model.SamplePair) (len=1 cap=1) {
    		-   (model.SamplePair) (0 @[1515580128.756]) {
    		-    Timestamp: (model.Time) (1515580128.756) 1515580128756,
    		-    Value: (model.SampleValue) (0) 0
    		-   }
    		+  Values: ([]model.SamplePair) {
    		   }
    		  })
    		 }
FAIL
FAIL	github.com/weaveworks/cortex/pkg/chunk	4.687s
```

### PR DESCRIPTION
**Pull request by jml**
`dummyChunkFor` was consulting the system clock itself. This meant that tests
like `TestChunkStore_Get` would intermittently fail, because _sometimes_ the
created chunks would have timestamps outside the window chosen within
`TestChunkStore_Get` (which itself consults the system clock).

This fixes the tests by making `now` a parameter of `dummyChunkFor`, which
makes the created chunks deterministic.

It also adds a `now` parameter to `dummyChunk`, which isn't strictly
necessary, but I believe is less error prone.

Fixes #646 

Thanks to @bboreham for the hint about `chunksToMatrix`, which helped narrow this down.

### CODE REVIEW

File: pkg/chunk/by_key_test.go [hunk 1]
```diff
@@ -102,7 +102,7 @@ func TestNWayIntersect(t *testing.T) {
 }
 
 func BenchmarkByKeyLess(b *testing.B) {
-	a := ByKey{dummyChunk(), dummyChunk()}
+	a := ByKey{dummyChunk(model.Now()), dummyChunk(model.Now())}
```
Comment (bboreham) [inline pkg/chunk/by_key_test.go]: even more deterministic to use the same value for these two calls?

File: pkg/chunk/chunk_test.go [hunk 2]
```diff
@@ -139,10 +139,10 @@ func TestChunksToMatrix(t *testing.T) {
 		"bar":  "baz",
 		"toms": "code",
 	}
-	chunk1 := dummyChunkFor(metric)
+	chunk1 := dummyChunkFor(model.Now(), metric)
```
Comment (bboreham) [inline pkg/chunk/chunk_test.go]: even more deterministic to use the same value of `now` here as at the beginning of the function?

File: pkg/chunk/chunk_test.go [hunk 3]
```diff
@@ -196,7 +196,7 @@ func TestChunksToMatrix(t *testing.T) {
 
 func benchmarkChunk() Chunk {
 	// This is a real example from Kubernetes' embedded cAdvisor metrics, lightly obfuscated
-	return dummyChunkFor(model.Metric{
+	return dummyChunkFor(model.Now(), model.Metric{
```
Comment (bboreham) [inline pkg/chunk/chunk_test.go]: I suspect `now` should be a parameter here so the benchmark can be as consistent as it wants to be

File: pkg/chunk/chunk_test.go [hunk 4]
```diff
@@ -157,7 +157,7 @@ func TestChunksToMatrix(t *testing.T) {
 		"bar":  "baz",
 		"toms": "code",
 	}
-	chunk3 := dummyChunkFor(otherMetric)
+	chunk3 := dummyChunkFor(model.Now(), otherMetric)
```
Comment (bboreham) [inline pkg/chunk/chunk_test.go]: ditto here on using same `now`

File: pkg/chunk/chunk_test.go [hunk 5]
```diff
@@ -139,10 +139,10 @@ func TestChunksToMatrix(t *testing.T) {
 		"bar":  "baz",
 		"toms": "code",
 	}
-	chunk1 := dummyChunkFor(metric)
+	chunk1 := dummyChunkFor(model.Now(), metric)
 	chunk1Samples, err := chunk1.Samples(chunk1.From, chunk1.Through)
 	require.NoError(t, err)
-	chunk2 := dummyChunkFor(metric)
+	chunk2 := dummyChunkFor(model.Now(), metric)
```
Comment (bboreham) [inline pkg/chunk/chunk_test.go]: ditto here on using same `now`

File: pkg/chunk/by_key_test.go (hunk 1 above)
Comment (jml) [reply pkg/chunk/by_key_test.go]: It would be. I'd like to communicate that the value doesn't matter and that the values can be different.

File: pkg/ingester/ingester_lifecycle.go [hunk 6]
```diff
@@ -127,6 +127,8 @@ func (i *Ingester) Shutdown() {
 }
 
 func (i *Ingester) loop() {
+	level.Debug(util.Logger).Log("msg", "we get logs in failed tests")
```
Comment (bboreham) [inline pkg/ingester/ingester_lifecycle.go]: is this meant to be here?

**Comment by jml** [comment]
Oops, no. That's from this morning's efforts to debug #369. Well spotted,
thanks.
