### PR TITLE
Retry failed terminal flushes at end of queue

### LINKED ISSUE #316: ValidationErrors while shutting down ingester
When shutting down an ingester for routine maintenance, I noticed an increase in chunk store flush failures due to "ValidationException":

screen shot 2017-03-07 at 12 10 55

Also, the series queue flush length stalled, rather than steadily decreased

screen shot 2017-03-07 at 12 11 36

Checking the logs, I saw lots of errors like these:

```
request id: DSCAO85A35JL2HLMUCPRPOMTSJVV4KQNSO5AEMVJF66Q9ASUAAJG" source="ingester.go:516"
time="2017-03-07T12:06:28Z" level=error msg="Failed to flush user: ValidationException: One or more parameter values were invalid: Aggregated size of all range keys has exceeded the size limit of 1024 bytes\n\tstatus code: 400, request id: O3EBMNFFUCSU252KDI1TKHTE9NVV4KQNSO5AEMVJF66Q9ASUAAJG"
```

This represents a serious problem, as we cannot shut down these ingesters cleanly.

### PR DESCRIPTION
**Pull request by jml**
See #316 

Had a stab at fixing this. Ended up coming up with two different solutions (commit 1 & commit 2 of this PR). One was to have a new slice-as-queue for storing failures, the other is to put the items back into the priority queue with an exponential "backoff". Not sure which I dislike least.

### CODE REVIEW

File: ingester/ingester.go [hunk 1]
```diff
@@ -523,23 +527,27 @@ func (i *Ingester) flushLoop(j int) {
...
-		for op.immediate && err != nil {
-			err = i.flushUserSeries(op.userID, op.fp, op.immediate)
-			if err != nil {
-				log.Errorf("Failed to flush user: %v", err)
+		// If we're exiting & we failed to flush, put the failed operation
+		// back in the queue at a later point.
+		if op.immediate && err != nil {
+			op.from = op.from.Add(backoff)
+			i.flushQueues[j].Enqueue(op)
+			backoff *= 2
```
Comment (tomwilkie) [inline ingester/ingester.go]: This backoff is going to be shared among all ops, right?

**Comment by tomwilkie** [comment]
I probably wouldn't bother with the exponential bit of the backoff, I'd just add a fixed amount on every failure.

Otherwise LGTM

**Comment by tomwilkie** [comment]
> Fixes #316

Not a fix...  a fix involves fixing the index too.

**Comment by jml** [comment]
> Not a fix... a fix involves fixing the index too.

Good point!
